# Generated by Django 3.1.2 on 2020-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
